### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by StrayDawg** [yusufklncc/Lenovo-Legion-5-Hackintosh#14]
I've tried four or five of your releases here with no luck...

All start with this duplicated image

![unnamed](https://user-images.githubusercontent.com/383448/234106702-b2794921-024a-4422-8e52-3fdc1b3e4bb7.jpg)

Is this the correct model number etc...
for this?

![image_123927839](https://user-images.githubusercontent.com/383448/234106870-1ba17d53-ca6e-4504-b616-0443014fece6.JPG)

**Comment by yusufklncc** [comment]
Try new release and installation steps.
