### ISSUE TITLE
How did you manage to disable egpu energy and have a battery life better?

### ISSUE THREAD

**Issue by GuilhermeCF10** [yusufklncc/Lenovo-Legion-5-Hackintosh#15]
How long does the battery last on average?

**Comment by housseinhareb** [comment]
I used this EFI, and it's lasting me an hour, 4 times worse than windows or linux. I haven't figured out a way to fix it.

**Comment by Hasinai** [comment]
You need patches for corrected disabled gGPU.
Same laptop, Mac OS X 13.3.1, opencore 0.9.1.
Watching movies 
3-3,5h (Mac OS X Ventura 13.3.1) (Little bit worse, maybe 15-20%)
3,5-4h (Windows 11).

**Comment by GuilhermeCF10** [comment]
I already imagined that Windows would have a better optimization, but yes, I still couldn't disable it, my battery is drained and in 20 minutes, it runs out.  I'm wondering about these patches, which one should I apply to disable this egpu, so maybe it lasts at least 2 hours.  Thank you so much guys

**Comment by Hasinai** [comment]
[patches_dgpu.zip](https://github.com/yusufklncc/Lenovo-Legion-5-Hackintosh/files/11418697/patches_dgpu.zip)
patches from 5T33Z0 works fine. In BIOS should disable Intel thermal framework (bcz fan spam)
SSDT-DGPU.aml disable dGPU on init
SSDT-EXT4.aml,SSDT-PTSWAKTTS.aml - for correct sleep-wake dgpu
also can share my config for touchpad, with correct GPIO Pin (1B)

**Comment by Engredaesm** [comment]
> can share my config for touchpad, with correct GPIO Pin (1B)

can you please share your config for touchpad, with correct GPIO Pin (1B

**Comment by Hasinai** [comment]
Works fine with latest VoodooI2C
opencore patch for replace
                <dict>
                    <key>Base</key>
                    <string></string>
                    <key>BaseSkip</key>
                    <integer>0</integer>
                    <key>Comment</key>
                    <string>_DSM to XTSM for TPD0</string>
                    <key>Count</key>
                    <integer>0</integer>
                    <key>Enabled</key>
                    <true/>
                    <key>Find</key>
                    <data>OV9EU00=</data>
                    <key>Limit</key>
                    <integer>0</integer>
                    <key>Mask</key>
                    <data></data>
                    <key>OemTableId</key>
                    <data></data>
                    <key>Replace</key>
                    <data>OVhUU00=</data>
                    <key>ReplaceMask</key>
                    <data></data>
                    <key>Skip</key>
                    <integer>0</integer>
                    <key>TableLength</key>
                    <integer>0</integer>
                    <key>TableSignature</key>
                    <data></data>
                </dict>
                <dict>
                    <key>Base</key>
                    <string></string>
                    <key>BaseSkip</key>
                    <integer>0</integer>
                    <key>Comment</key>
                    <string>_CRS to XCRS for TPD0</string>
                    <key>Count</key>
                    <integer>0</integer>
                    <key>Enabled</key>
                    <true/>
                    <key>Find</key>
                    <data>RwdfQ1JT</data>
                    <key>Limit</key>
                    <integer>0</integer>
                    <key>Mask</key>
                    <data></data>
                    <key>OemTableId</key>
                    <data></data>
                    <key>Replace</key>
                    <data>RwdYQ1JT</data>
                    <key>ReplaceMask</key>
                    <data></data>
                    <key>Skip</key>
                    <integer>0</integer>
                    <key>TableLength</key>
                    <integer>0</integer>
                    <key>TableSignature</key>
                    <data></data>
                </dict>

SSDT-TPD0.aml - ACPI patch
[SSDT-TPD0.TAR.GZ](https://github.com/yusufklncc/Lenovo-Legion-5-Hackintosh/files/11438231/SSDT-TPD0.TAR.GZ)
![image](https://github.com/yusufklncc/Lenovo-Legion-5-Hackintosh/assets/105512037/d02197a9-fb05-4408-a578-5d4caaac4957)

**Comment by Engredaesm** [comment]
> Works fine with latest VoodooI2C opencore patch for replace (XTSM,XCRS for Touchpad) ![image](https://user-images.githubusercontent.com/105512037/237283066-37e5ebcd-be57-4f69-ae63-b47a7518b026.png)
> 
> ` <dict> <key>Base</key> <string></string> <key>BaseSkip</key> <integer>0</integer> <key>Comment</key> <string>_DSM to XTSM for TPD0</string> <key>Count</key> <integer>0</integer> <key>Enabled</key> <true/> <key>Find</key> <data>OV9EU00=</data> <key>Limit</key> <integer>0</integer> <key>Mask</key> <data></data> <key>OemTableId</key> <data></data> <key>Replace</key> <data>OVhUU00=</data> <key>ReplaceMask</key> <data></data> <key>Skip</key> <integer>0</integer> <key>TableLength</key> <integer>0</integer> <key>TableSignature</key> <data></data> </dict> <dict> <key>Base</key> <string></string> <key>BaseSkip</key> <integer>0</integer> <key>Comment</key> <string>_CRS to XCRS for TPD0</string> <key>Count</key> <integer>0</integer> <key>Enabled</key> <true/> <key>Find</key> <data>RwdfQ1JT</data> <key>Limit</key> <integer>0</integer> <key>Mask</key> <data></data> <key>OemTableId</key> <data></data> <key>Replace</key> <data>RwdYQ1JT</data> <key>ReplaceMask</key> <data></data> <key>Skip</key> <integer>0</integer> <key>TableLength</key> <integer>0</integer> <key>TableSignature</key> <data></data> </dict>`
> 
> SSDT-TPD0.aml - ACPI patch [SSDT-TPD0.TAR.GZ](https://github.com/yusufklncc/Lenovo-Legion-5-Hackintosh/files/11438231/SSDT-TPD0.TAR.GZ) ![image](https://user-images.githubusercontent.com/105512037/237282761-d02197a9-fb05-4408-a578-5d4caaac4957.png)

thank you very much worked like a charm for me

**Comment by yusufklncc** [comment]
I am using this method.
![CleanShot 2023-05-21 at 17 19 58](https://github.com/yusufklncc/Lenovo-Legion-5-Hackintosh/assets/78423442/4479da4b-eddf-4840-9683-7354bf439e8f)

Because when i use SSDT. My fans are going %100 and after a little time laptop restart.
