### ISSUE TITLE
Diaplay mem 8mb

### ISSUE THREAD

**Issue by orcl2** [yusufklncc/Lenovo-Legion-5-Hackintosh#18]
Hi, first of all, thanks for the EFI, it's a great job.

I'm facing this issue, where the iGPU memory is in 8mb, and even with some help from the community, i'm not getting able to increase the amount of iGPU memomry.

**Comment by orcl2** [comment]
I7-10750H

**Comment by yusufklncc** [comment]
Try again latest release. Follow steps and set your BIOS.

**Comment by orcl2** [comment]
I'm gonna try again, be right back with de results.

**Comment by orcl2** [comment]
I did again, with your latest efi release, but now the laptop turns the fan very aggressively and when I do the login, the laptop turns it self off. Any suggestions?

*Seems that the issue with the graphic card was solved

**Comment by yusufklncc** [comment]
For fan issue: https://github.com/yusufklncc/Lenovo-Legion-5-Hackintosh#setting-bios-settings

**Comment by orcl2** [comment]
I did this configuration, and not worked, something else I can try?

**Comment by yusufklncc** [comment]
Are you sure? Did you disable Intel Thermal Framework (DPTF)? This must solve the fan issue. İf not working disabled DGPU.aml and add -wegnoegpu argument.

**Comment by orcl2** [comment]
Yes, i disabled the DPTF  in BIOs, I'll try to disabling the DGPU

**Comment by orcl2** [comment]
I tested and reinstalled the MacOS, worked very well, thank you very much @yusufklncc

**Comment by yusufklncc** [comment]
Did you success with disabled DGPU?

**Comment by yusufklncc** [comment]
And how did you fix backlight?

**Comment by orcl2** [comment]
> Did you success with disabled DGPU?

Yes, i dos what you suggested and I did reinstall the macos

**Comment by orcl2** [comment]
> And how did you fix backlight?

I didn't, i Just Power off and on again kkkk

**Comment by orcl2** [comment]
But, seems that i have one issue left, It is restarting when goes to sleep mode
