### ISSUE TITLE
No Gui

### ISSUE THREAD

**Issue by Amaryaser9** [yusufklncc/Lenovo-Legion-5-Hackintosh#4]
Please please help me that is so important for me.
I have used your efi to install Mac OS Monterey 12.5.1 to my legion 5 laptop (my model ends with 05 not 05H but it is actually the same device although the discrete graphics is Nvidia GTX 1650 TI)
it is the best efi which helped me a lot but I face a big problem
I made the macOS recovery boot usb via windows and it is okay but the recovery itself have no GUI although it actually running and  make sounds and take orders but no gui 
I were on the dynamic graphic as the Mac will use the iGPU but when I faced this problem I turned it to "disceate graphics" and the recovery finally got a gui but after installation the Mac OS not recognizing the discrete graphics as he works on the Nvidia card now and it show as "display 8 mb" so you know it is so laggy and ui is terrible
and when I switch graphics from bios to dynamic there is no gui
please help me I need this to work as fast as possible because I am a student in a faculty of computer science and I have many apps I need to run on it so I really need you to help me to fix this issue. 
Thank you for understanding.

**Comment by Amaryaser9** [comment]
![screenshot1](https://user-images.githubusercontent.com/90965104/186394675-09ce16d1-8ca8-473a-904b-f57f958270f6.png)
this is the graphics card when I set it to "discrete graphics" in bios
but no gui when "Dynamic graphics"
pls help me

**Comment by ZeyadShawki** [comment]
same lenovo legion 5 3050ti model  15mh6 same exact problem it display 8mb only on graphic card

**Comment by ZeyadShawki** [comment]
same lenovo legion 5 3050ti model  15mh6 same exact problem it display 8mb only on graphic card macos montery

**Comment by Amaryaser9** [comment]
> same lenovo legion 5 3050ti model 15mh6 same exact problem it display 8mb only on graphic card macos montery
in discrete graphics right?
so could you find a solution ?!
this is so important for me to be able to solve it

**Comment by ZeyadShawki** [comment]
didi u try to install bigsur?

**Comment by ZeyadShawki** [comment]
i tried alot alot of edit in congig.plist for intel uhd630 to work no luck

**Comment by Amaryaser9** [comment]
the same problem 
you used the discrete graphics right?

**Comment by ZeyadShawki** [comment]
the discrete gpu should not work bec. it is not supported the problem is that ssdt controller should disable the dgpu and work only on what is supported that is intel uhd630 but i tried alot of methods nothing work and the graphic card vram still only 8mb and it should be more than 1000mb

**Comment by ZeyadShawki** [comment]
thu aurther have 2060 gpu dont know if its the cause of the problem but i opened the ssdt controller it the same name of my gpu so it should work

**Comment by Amaryaser9** [comment]
بص يا زياد من الاخر كدا ابعت الواتس او اي حاجه اكلمك احسن لان واضح ان صاحب الريبو دي مش هيرد دلوقتي ف كلمني نشوف حل سوا @ZeyadShawki

**Comment by ZeyadShawki** [comment]
01228424745

**Comment by ZeyadShawki** [comment]
01228414745
