### ISSUE TITLE
core i5 problem

### ISSUE THREAD

**Issue by thetazby** [yusufklncc/Lenovo-Legion-5-Hackintosh#6]
dont work with core i5 10300h, i'm noob, plz help

**Comment by yusufklncc** [comment]
What is the latest status?

**Comment by AesmaDiv** [comment]
Legion 5Pi (10300h/1660Ti)
Repeatedly tried to upgrade from BigSur to Monterey. Stuck at AppleACPICpu message. Nothing helped. Already desperate. But your EFI worked like charm. Updated to Ventura. Thanks bro.

**Comment by yusufklncc** [comment]
Oh thanks. I'm glad it worked for you
